
default: &default
  encoding: unicode
  adapter: postgresql
  host: localhost
  username: obp
  password: obp
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: obp_dev

test:
  <<: *default
  database: obp_test

production:
  <<: *default
  database: obp
